name: KIII Project CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: elganchoo/ebookshop
        run: |
          docker-compose -f web/docker-compose.yml build
          docker-compose -f web/docker-compose.yml push

      # Add more steps for testing, linting, etc.

      - name: Deploy to production (example)
        if: success()  # Example: deploy only if all previous steps succeed
        run: |
          docker-compose -f web/docker-compose.yml down
          docker-compose -f web/docker-compose.yml pull
          docker-compose -f web/docker-compose.yml up -d

