name: KIII Project CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create docker image name
        id: docker-image
        run: |
            BRANCH_NAME=${{ github.ref_name }}
            IMAGE_NAME=${BRANCH_NAME}_${{ github.sha }}
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
      - name: Extract repository name
        id: extract-repository-name
        run: |
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
            echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_OUTPUT
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: Dockerfile
          push: true
          tags: >
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract-repository-name.outputs.REPO_NAME }}:${{ steps.docker-image.outputs.IMAGE_NAME }}


      - name: Deploy to production (example)
        if: success() 
        run: |
          docker-compose -f web/docker-compose.yml down
          docker-compose -f web/docker-compose.yml pull
          docker-compose -f web/docker-compose.yml up -d

